POST http://localhost:6900/auth/register/ 
content-type: application/json

{
    "phone_num":98989898,
    "name":"yashhh",
    "email":"yashraj@gmail.com",
    "password":"123",
    "Wishlist":["hdaskdfhksd","dsjkfasjkd","sdjflaksjf"]
}
